spring:
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo-auth
  redis:
    host: 192.168.160.201
    port: 6379
    password: palmpass&8584!-redis-m!ser
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fegindemo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8089
logging:
  level:
    root: debug
